"""
Mock inputs for testing the Critic Agent.

The advisor report intentionally contains overconfident statements and omitted
risks so the critic has something meaningful to challenge.
"""

from ai_integration.agent2_advisor.mock_data import MOCK_CONTEXT_DOCS, USER_QUERY


MOCK_ADVISOR_REPORT = """
=== FINAL REPORT GENERATED BY ADVISOR AGENT ===

# Tesla, Inc. Financial Health and Future Outlook

## Key Financial Metrics (2022)

The following table summarizes Tesla's key financial metrics as of December 31, 2022:

| Metric                           | Value       |
|----------------------------------|-------------|
| Total Revenues (Sales)          | $81,462M    |
| Income from Operations (EBIT)    | $13,656M    |
| Total Assets                     | $82,338M    |
| Total Liabilities                | $36,440M    |
| Retained Earnings                 | $12,885M    |
| Working Capital                   | $14,208M    |
| Market Capitalization             | $389,000M   |
| Total Debt                       | $5,748M     |
| Interest Expense                  | $191M       |

*Source: NASDAQ_TSLA_2022.pdf (Part II, Item 8) - Consolidated Balance Sheets & Operations*

## Financial Health Assessment

### 1. **Risk Assessment**
- **Altman Z-Score**: 8.367 (Safe Zone - Low Bankruptcy Risk)
  - This score indicates that Tesla is in a strong financial position with a low risk of bankruptcy.
  
- **Debt to Equity Ratio**: 0.1252
  - This low ratio suggests that Tesla is not heavily reliant on debt to finance its operations, which is a positive indicator of financial stability.

- **Interest Coverage Ratio**: 71.5
  - This high ratio indicates that Tesla generates significantly more earnings than it needs to cover its interest expenses, demonstrating strong operational efficiency.

### 2. **Working Capital**
- **Working Capital**: $14,208M
  - This positive working capital indicates that Tesla has sufficient short-term assets to cover its short-term liabilities, which is essential for maintaining operational liquidity.

### 3. **Market Capitalization**
- **Market Capitalization**: $389,000M
  - A high market cap reflects strong investor confidence and a robust market position.

## Future Outlook

Tesla's future outlook appears promising due to several factors:

- **Innovative Technology**: Tesla's advancements in battery technology and autonomous driving systems position it well for future growth in the electric vehicle market.
- **Global Manufacturing Presence**: With multiple Gigafactories worldwide, Tesla can mitigate supply chain risks and reduce costs associated with transportation and tariffs.
- **Government Incentives**: The Inflation Reduction Act provides significant incentives for electric vehicle purchases, which could boost sales and market penetration.

### Risks and Limitations
While Tesla's financial health is strong, several risks could impact its future outlook:

- **Supply Chain Vulnerabilities**: Dependency on single-source suppliers for key components may pose risks of supply chain disruptions.
- **Market Competition**: The electric vehicle market is becoming increasingly competitive, with traditional automakers and new entrants investing heavily in EV technology.
- **Regulatory Changes**: Changes in government policies or incentives related to electric vehicles could affect demand.

### Actionable Advice
1. **Diversify Supply Chain**: Tesla should consider diversifying its supplier base to mitigate risks associated with single-source dependencies.
2. **Enhance Competitive Position**: Continued investment in R&D for battery technology and autonomous driving features will help maintain a competitive edge.
3. **Monitor Regulatory Environment**: Staying informed about regulatory changes and adapting strategies accordingly will be crucial for sustaining growth.

## Conclusion

Overall, Tesla demonstrates strong financial health with low bankruptcy risk, efficient operations, and a solid market position. The company's focus on innovation and global manufacturing capabilities further enhances its potential for future growth. However, addressing supply chain vulnerabilities and monitoring market competition will be essential for sustaining its success.

For a visual representation of Tesla's key financial metrics, please refer to the table below:

| Metric                           | Value       |
|----------------------------------|-------------|
| Total Revenues (Sales)          | $81,462M    |
| Income from Operations (EBIT)    | $13,656M    |
| Total Assets                     | $82,338M    |
| Total Liabilities                | $36,440M    |
| Retained Earnings                 | $12,885M    |
| Working Capital                   | $14,208M    |
| Market Capitalization             | $389,000M   |
| Total Debt                       | $5,748M     |
| Interest Expense                  | $191M       |

*Source: NASDAQ_TSLA_2022.pdf (Part II, Item 8) - Consolidated Balance Sheets & Operations*

=== TEST COMPLETED SUCCESSFULLY ===
"""
