"""
Test runner for the Critic Agent.
Uses mock Tesla context and a deliberately flawed advisor report.
"""

import os
import sys
from pathlib import Path


project_root = str(Path(__file__).resolve().parents[2])
if project_root not in sys.path:
    sys.path.insert(0, project_root)

from ai_integration.agent3_critic.critic import CriticAgent
from ai_integration.agent3_critic.mock_data import MOCK_ADVISOR_REPORT, MOCK_CONTEXT_DOCS, USER_QUERY
from ai_integration.agent3_critic.tools import (
    critique_quality_tool,
    evidence_consistency_tool,
    report_coverage_tool,
    risk_gap_tool,
)


def run_offline_tool_checks() -> None:
    print("=== OFFLINE CRITIC TOOL CHECKS ===")
    print("\n[Coverage]")
    print(report_coverage_tool(USER_QUERY, MOCK_ADVISOR_REPORT))
    print("\n[Evidence]")
    print(evidence_consistency_tool(MOCK_ADVISOR_REPORT, MOCK_CONTEXT_DOCS))
    print("\n[Risk Gaps]")
    print(risk_gap_tool(MOCK_ADVISOR_REPORT, MOCK_CONTEXT_DOCS))
    print("\n[Quality Self-Check Sample]")
    print(critique_quality_tool("## Overall Verdict\nInvestor concern: unsupported claim."))


def main() -> None:
    print("=== STARTING CRITIC AGENT TEST ===")
    print(f"Project root added to path: {project_root}")
    print("Targeting model: gpt-4o-mini")
    print(f"User Query:\n{USER_QUERY}\n")

    run_offline_tool_checks()

    from dotenv import load_dotenv

    env_path = Path(project_root) / "backend" / ".env"
    load_dotenv(dotenv_path=str(env_path))

    if not os.getenv("OPENAI_API_KEY"):
        print("\n[SKIP] OPENAI_API_KEY is missing. Offline tool checks completed.")
        return

    agent = CriticAgent(model="gpt-4o-mini")
    try:
        final_critique = agent.run(USER_QUERY, MOCK_CONTEXT_DOCS, MOCK_ADVISOR_REPORT)
    except Exception as exc:
        print(f"\n[SKIP] OpenAI call failed: {exc}")
        print("Offline tool checks completed. Re-run with network access to test the full LLM loop.")
        return

    print("\n=== FINAL CRITIQUE GENERATED BY CRITIC AGENT ===\n")
    print(final_critique)
    print("\n=== TEST COMPLETED SUCCESSFULLY ===")


if __name__ == "__main__":
    main()
