"""
Test runner for the Advisor Agent.
Loads simulated Tesla 2022 10-K data and runs the agent to generate suggestions.
"""

import os
import sys
from pathlib import Path

# Add project root to Python path so we can run this module directly
project_root = str(Path(__file__).resolve().parents[2])
if project_root not in sys.path:
    sys.path.insert(0, project_root)

from ai_integration.agent2_advisor.advisor import AdvisorAgent
from ai_integration.agent2_advisor.mock_data import USER_QUERY, MOCK_CONTEXT_DOCS

def main():
    print("=== STARTING ADVISOR AGENT TEST ===")
    print(f"Project root added to path: {project_root}")
    print(f"Targeting model: gpt-4o-mini")
    print(f"User Query:\n{USER_QUERY}\n")
    
    # Check for OpenAI key
    from dotenv import load_dotenv
    ENV_PATH = Path(project_root) / "backend" / ".env"
    load_dotenv(dotenv_path=str(ENV_PATH))
    
    if not os.getenv("OPENAI_API_KEY"):
        print("[ERROR] OPENAI_API_KEY is missing! Please make sure it is defined in backend/.env")
        sys.exit(1)
        
    try:
        # Initialize the Agent
        agent = AdvisorAgent(model="gpt-4o-mini")
        
        # Run the Agent
        print("Running agent (this will trigger tool calls for Framework templates and Risk Assessment)...")
        final_report = agent.run(USER_QUERY, MOCK_CONTEXT_DOCS)
        
        print("\n=== FINAL REPORT GENERATED BY ADVISOR AGENT ===\n")
        print(final_report)
        print("\n=== TEST COMPLETED SUCCESSFULLY ===")
        
    except Exception as e:
        print(f"\n[ERROR] An error occurred while running the test: {e}")
        import traceback
        traceback.print_exc()

if __name__ == "__main__":
    main()
