"""
Test runner for the Advisor Agent's Revision Process.
Loads mock advisor v1 report, mock critic feedback, and runs the revision logic to output V2.
"""

import os
import sys
from pathlib import Path

# Add project root to Python path so we can run this module directly
project_root = str(Path(__file__).resolve().parents[2])
if project_root not in sys.path:
    sys.path.insert(0, project_root)

from ai_integration.agent2_advisor.advisor import AdvisorAgent
from ai_integration.agent2_advisor.mock_data_revision import (
    USER_QUERY,
    MOCK_CONTEXT_DOCS,
    MOCK_ADVISOR_REPORT_V1,
    MOCK_CRITIC_FEEDBACK,
)

def main():
    print("=== STARTING ADVISOR REVISION TEST ===")
    print(f"Project root added to path: {project_root}")
    print(f"Targeting model: gpt-4o-mini")
    
    # Check for OpenAI key
    from dotenv import load_dotenv
    ENV_PATH = Path(project_root) / "backend" / ".env"
    load_dotenv(dotenv_path=str(ENV_PATH))
    
    if not os.getenv("OPENAI_API_KEY"):
        print("[ERROR] OPENAI_API_KEY is missing! Please make sure it is defined in backend/.env")
        sys.exit(1)
        
    try:
        # Initialize the Agent
        agent = AdvisorAgent(model="gpt-4o-mini")
        
        # Build the background context description for the model
        context_str = agent._build_context_string(MOCK_CONTEXT_DOCS)
        
        # Run the revision logic manually using the mock inputs
        print("Running revision (this will trigger tool calls to address critic issues)...")
        revised_report = agent._revise_report(
            query=USER_QUERY,
            context_str=context_str,
            current_report=MOCK_ADVISOR_REPORT_V1,
            self_check=MOCK_CRITIC_FEEDBACK
        )
        
        print("\n=== REVISED REPORT GENERATED BY ADVISOR AGENT (V2) ===\n")
        print(revised_report)
        print("\n=== REVISION TEST COMPLETED SUCCESSFULLY ===")
        
    except Exception as e:
        print(f"\n[ERROR] An error occurred while running the test: {e}")
        import traceback
        traceback.print_exc()

if __name__ == "__main__":
    main()
